/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VertexDashboardRouteImport } from './routes/vertex-dashboard'
import { Route as UserSettingsRouteImport } from './routes/user-settings'
import { Route as SecurityPrivacyRouteImport } from './routes/security-privacy'
import { Route as SchoolOnboardingRouteImport } from './routes/school-onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminSettingsRouteImport } from './routes/admin-settings'
import { Route as AdminIntegrationsRouteImport } from './routes/admin-integrations'
import { Route as AdminAuditLogRouteImport } from './routes/admin-audit-log'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiViewDocumentRouteImport } from './routes/api/view-document'
import { Route as ApiAiHelperRouteImport } from './routes/api/ai-helper'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAsanaOauthStartRouteImport } from './routes/api/asana/oauth/start'
import { Route as ApiAsanaOauthDisconnectRouteImport } from './routes/api/asana/oauth/disconnect'
import { Route as ApiAsanaOauthCallbackRouteImport } from './routes/api/asana/oauth/callback'

const VertexDashboardRoute = VertexDashboardRouteImport.update({
  id: '/vertex-dashboard',
  path: '/vertex-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityPrivacyRoute = SecurityPrivacyRouteImport.update({
  id: '/security-privacy',
  path: '/security-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolOnboardingRoute = SchoolOnboardingRouteImport.update({
  id: '/school-onboarding',
  path: '/school-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin-integrations',
  path: '/admin-integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin-audit-log',
  path: '/admin-audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiViewDocumentRoute = ApiViewDocumentRouteImport.update({
  id: '/api/view-document',
  path: '/api/view-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiHelperRoute = ApiAiHelperRouteImport.update({
  id: '/api/ai-helper',
  path: '/api/ai-helper',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAsanaOauthStartRoute = ApiAsanaOauthStartRouteImport.update({
  id: '/api/asana/oauth/start',
  path: '/api/asana/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAsanaOauthDisconnectRoute = ApiAsanaOauthDisconnectRouteImport.update({
  id: '/api/asana/oauth/disconnect',
  path: '/api/asana/oauth/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAsanaOauthCallbackRoute = ApiAsanaOauthCallbackRouteImport.update({
  id: '/api/asana/oauth/callback',
  path: '/api/asana/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-audit-log': typeof AdminAuditLogRoute
  '/admin-integrations': typeof AdminIntegrationsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/login': typeof LoginRoute
  '/school-onboarding': typeof SchoolOnboardingRoute
  '/security-privacy': typeof SecurityPrivacyRoute
  '/user-settings': typeof UserSettingsRoute
  '/vertex-dashboard': typeof VertexDashboardRoute
  '/api/ai-helper': typeof ApiAiHelperRoute
  '/api/view-document': typeof ApiViewDocumentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/asana/oauth/callback': typeof ApiAsanaOauthCallbackRoute
  '/api/asana/oauth/disconnect': typeof ApiAsanaOauthDisconnectRoute
  '/api/asana/oauth/start': typeof ApiAsanaOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-audit-log': typeof AdminAuditLogRoute
  '/admin-integrations': typeof AdminIntegrationsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/login': typeof LoginRoute
  '/school-onboarding': typeof SchoolOnboardingRoute
  '/security-privacy': typeof SecurityPrivacyRoute
  '/user-settings': typeof UserSettingsRoute
  '/vertex-dashboard': typeof VertexDashboardRoute
  '/api/ai-helper': typeof ApiAiHelperRoute
  '/api/view-document': typeof ApiViewDocumentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/asana/oauth/callback': typeof ApiAsanaOauthCallbackRoute
  '/api/asana/oauth/disconnect': typeof ApiAsanaOauthDisconnectRoute
  '/api/asana/oauth/start': typeof ApiAsanaOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-audit-log': typeof AdminAuditLogRoute
  '/admin-integrations': typeof AdminIntegrationsRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/login': typeof LoginRoute
  '/school-onboarding': typeof SchoolOnboardingRoute
  '/security-privacy': typeof SecurityPrivacyRoute
  '/user-settings': typeof UserSettingsRoute
  '/vertex-dashboard': typeof VertexDashboardRoute
  '/api/ai-helper': typeof ApiAiHelperRoute
  '/api/view-document': typeof ApiViewDocumentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/asana/oauth/callback': typeof ApiAsanaOauthCallbackRoute
  '/api/asana/oauth/disconnect': typeof ApiAsanaOauthDisconnectRoute
  '/api/asana/oauth/start': typeof ApiAsanaOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-audit-log'
    | '/admin-integrations'
    | '/admin-settings'
    | '/login'
    | '/school-onboarding'
    | '/security-privacy'
    | '/user-settings'
    | '/vertex-dashboard'
    | '/api/ai-helper'
    | '/api/view-document'
    | '/api/auth/$'
    | '/api/asana/oauth/callback'
    | '/api/asana/oauth/disconnect'
    | '/api/asana/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-audit-log'
    | '/admin-integrations'
    | '/admin-settings'
    | '/login'
    | '/school-onboarding'
    | '/security-privacy'
    | '/user-settings'
    | '/vertex-dashboard'
    | '/api/ai-helper'
    | '/api/view-document'
    | '/api/auth/$'
    | '/api/asana/oauth/callback'
    | '/api/asana/oauth/disconnect'
    | '/api/asana/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-audit-log'
    | '/admin-integrations'
    | '/admin-settings'
    | '/login'
    | '/school-onboarding'
    | '/security-privacy'
    | '/user-settings'
    | '/vertex-dashboard'
    | '/api/ai-helper'
    | '/api/view-document'
    | '/api/auth/$'
    | '/api/asana/oauth/callback'
    | '/api/asana/oauth/disconnect'
    | '/api/asana/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  LoginRoute: typeof LoginRoute
  SchoolOnboardingRoute: typeof SchoolOnboardingRoute
  SecurityPrivacyRoute: typeof SecurityPrivacyRoute
  UserSettingsRoute: typeof UserSettingsRoute
  VertexDashboardRoute: typeof VertexDashboardRoute
  ApiAiHelperRoute: typeof ApiAiHelperRoute
  ApiViewDocumentRoute: typeof ApiViewDocumentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAsanaOauthCallbackRoute: typeof ApiAsanaOauthCallbackRoute
  ApiAsanaOauthDisconnectRoute: typeof ApiAsanaOauthDisconnectRoute
  ApiAsanaOauthStartRoute: typeof ApiAsanaOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vertex-dashboard': {
      id: '/vertex-dashboard'
      path: '/vertex-dashboard'
      fullPath: '/vertex-dashboard'
      preLoaderRoute: typeof VertexDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-settings': {
      id: '/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-privacy': {
      id: '/security-privacy'
      path: '/security-privacy'
      fullPath: '/security-privacy'
      preLoaderRoute: typeof SecurityPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-onboarding': {
      id: '/school-onboarding'
      path: '/school-onboarding'
      fullPath: '/school-onboarding'
      preLoaderRoute: typeof SchoolOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-settings': {
      id: '/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-integrations': {
      id: '/admin-integrations'
      path: '/admin-integrations'
      fullPath: '/admin-integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-audit-log': {
      id: '/admin-audit-log'
      path: '/admin-audit-log'
      fullPath: '/admin-audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/view-document': {
      id: '/api/view-document'
      path: '/api/view-document'
      fullPath: '/api/view-document'
      preLoaderRoute: typeof ApiViewDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-helper': {
      id: '/api/ai-helper'
      path: '/api/ai-helper'
      fullPath: '/api/ai-helper'
      preLoaderRoute: typeof ApiAiHelperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asana/oauth/start': {
      id: '/api/asana/oauth/start'
      path: '/api/asana/oauth/start'
      fullPath: '/api/asana/oauth/start'
      preLoaderRoute: typeof ApiAsanaOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asana/oauth/disconnect': {
      id: '/api/asana/oauth/disconnect'
      path: '/api/asana/oauth/disconnect'
      fullPath: '/api/asana/oauth/disconnect'
      preLoaderRoute: typeof ApiAsanaOauthDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asana/oauth/callback': {
      id: '/api/asana/oauth/callback'
      path: '/api/asana/oauth/callback'
      fullPath: '/api/asana/oauth/callback'
      preLoaderRoute: typeof ApiAsanaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  LoginRoute: LoginRoute,
  SchoolOnboardingRoute: SchoolOnboardingRoute,
  SecurityPrivacyRoute: SecurityPrivacyRoute,
  UserSettingsRoute: UserSettingsRoute,
  VertexDashboardRoute: VertexDashboardRoute,
  ApiAiHelperRoute: ApiAiHelperRoute,
  ApiViewDocumentRoute: ApiViewDocumentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAsanaOauthCallbackRoute: ApiAsanaOauthCallbackRoute,
  ApiAsanaOauthDisconnectRoute: ApiAsanaOauthDisconnectRoute,
  ApiAsanaOauthStartRoute: ApiAsanaOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
